import { useContext } from "react";
import Head from "next/head";
import Nav from "../components/Nav";
import { ThemeContext } from "../context/ThemeProvider";
// import styles from "../styles/Home.module.css";

export default function Home() {
  const {theme, setTheme, changeTheme} = useContext(ThemeContext)
  return (
    <>
      <Head>
        <title>Crudu Alexandru Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={`app ${theme}`}>
          <Nav />
          <div className="w-screen h-screen">test full width takes body color</div>
        </div>
    </>
  );
}
