import Head from "next/head";
import { useContext } from "react";
import { ThemeContext } from "../context/ThemeProvider";
import Nav from "../components/Nav";
import Introduction from "../components/Introduction";
import Projects from "../components/Projects";
import Menu from "../components/Menu";
import About from "../components/About";
import Footer from "../components/Footer";
import ContactForm from "../components/ContactForm";
import InfiniteLogoSlider from "../components/InfiniteLogoSlider";

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

export default function Home() {
  const { theme } = useContext(ThemeContext);

  return (
    <>
      <Head>
        <title>Crudu Alexandru Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/images/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/images/favicon-16x16.png"
        />
        <link rel="mask-icon" href="/images/favicon.ico" color="#000000"></link>
      </Head>
      <main className={`app ${theme} overscroll-none overflow-x-hidden`}>
        <Nav />
        <Menu />
        <Introduction />
        <Projects />
        <About />
        <InfiniteLogoSlider />
        <ContactForm />
        <Footer />
      </main>
    </>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'common',
      ])),
    },
  }
}